import type { Metadata } from 'next'
import './globals.css'
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'
import { AppSidebar } from '@/components/app-sidebar'
import { auth } from '@/auth'

export const metadata: Metadata = {
  title: 'Skill Chronicle',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()

  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          {session && <AppSidebar session={session} />}
          <main className="w-full">
            {session && <SidebarTrigger />}
            <div className="w-full flex justify-center">{children}</div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  )
}
